---
version: "3.9"

services:
  doe-dates:
    image: angeltrs/doe-dates:latest
    container_name: doe-dates
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - TZ=America/New_York
    ports:
      - "8106:80"
    restart: unless-stopped
