---
version: "3.9"

services:
  doe-dates:
    container_name: doe-dates
    image: angeltrs/doe-dates:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - TZ=America/New_York
    ports:
      - "8106:80"
