name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-and-build:
    environment: production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "~/angeltrs/doe-dates"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd "~/angeltrs/doe-dates"
          docker-compose down
          docker-compose up --build -d
